### ISSUE TITLE
下载不了模型

### ISSUE THREAD

**Issue by nigo81** [linyiLYi/bilibot#2]
执行python3 -m mlx_lm.lora --model models/Qwen1.5-32B-Chat --data data/ --train --iters 1000 --batch-size 16 --lora-layers 12报错：

`Repository Not Found for url: https://huggingface.co/api/models/models/Qwen1.5-32B-Chat/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.`

已开启科学上网。请问怎么解决呢？另外我使用ollama在本地是安装有qwen:32b-chat的，可以怎么直接利用吗？

**Comment by nigo81** [comment]
已解决。直接在[huggingface](https://huggingface.co/Qwen/Qwen1.5-32B-Chat/tree/main)或者[魔塔](https://modelscope.cn/models/qwen/Qwen1.5-32B-Chat/files)上克隆下来，放在`models`文件夹下就可以了。魔塔不需要科学上网。

**Comment by greenhand0403** [comment]
> `放在models文件夹下` 具体指哪一个文件夹？

**Comment by zhenaiwork** [comment]
> > `放在models文件夹下` 具体指哪一个文件夹？
没有的话直接在项目跟目录自己创建一个

**Comment by nigo81** [comment]
> > > `放在models文件夹下` 具体指哪一个文件夹？
> > > 没有的话直接在项目跟目录自己创建一个

克隆在`bilibot/models`文件夹下，比如克隆后，我的就是`bilibot/models/Qwen1.5-32B-Chat`

**Comment by bdim404** [comment]
这玩意 git clone 的时候也没有一个进度显示啥的，我看网路流量接收大包才知道在下载模型呢，绝了。
