### ISSUE TITLE
 pip install -r requirements.txt  失败

### ISSUE THREAD

**Issue by biingxiing** [linyiLYi/bilibot#21]
提示
ERROR: Could not find a version that satisfies the requirement mlx (from versions: none)
ERROR: No matching distribution found for mlx

我是应该添加不同的源吗

**Comment by arpy8** [comment]
`mlx` is available only for macos.

https://stackoverflow.com/questions/77809776/no-matching-distribution-found-for-mlx

**Comment by biingxiing** [comment]
update mac version from 13.5.1 to 14.5 and use
`conda install conda-forge::mlx`
problem is fixed
